
---

## How to View the Dashboard

1. Download the `.pbix` file from the repository  
2. Open it using **Power BI Desktop**  
3. Use slicers to interact with outlet location, size, and item type  

---

## Author

**Tejas Kapse**  
Aspiring Data Analyst  
GitHub: https://github.com/your-username  

---

## Tags

Power BI • Data Analytics • Business Intelligence • Dashboard • Sales Analysis • Retail Analytics
